VueCalculator
js-tasks-ru/vue-20220125_natali272014 pull request #3
Opened 2022-01-30 14:54 UTC by NataliKh

VueCalculator

2022-01-31 23:39 UTC, ShGKme commented
У вас конфликт в PR.

Попробуйте выполнить команды:
```git
git pull upstream master
git push origin master
```

2022-02-01 15:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-01 20:27 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-02 06:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-02-02 14:27 UTC, ShGKme requested changes
В `02-VueCalculator` требуется двустороннее связывание радиокнопок. В остальном всё хорошо, остальные задачи приняты.

2022-02-02 14:27 UTC, ShGKme commented on 01-basics/02-VueCalculator/index.html
> +      </div>
Короткий комментарий: вместо обработки клика требуется двустороннее связывание.

---

Подробнее.

В текущем решении при клике на радиокнопку обновляется `actions` через обработку клика: `@click="actions='+'"`.

Но, выбрана ли конкретная радиокнопка, никак не привязано к состоянию компонента. `checked` радиокнопки не определён.

Это плохо по двум причинам:
1. Если `actions` вдруг поменяется не кликом, то радиокнопки не поменяются. Например, если сейчас на радиокнопках выбрано деление `/`, а потом в приложение выполнят `actions = "+"`, на странице так и останется старое выбранное значение с делением.

2. Есть риск, что при обновлении компонента потеряется выбор на радиокнопке (он никак не определяется в самом приложении).

Чтобы этого избежать, требуется всегда привязывать элементы форм к состоянию приложения. Например, в случае радиокнопок это можно сделать через привязку: `:checked="actions === '+'"`.

В итоге получается полноценное двустороннее связывание:
1. Состояние радиокнопки определяется состоянием компонента через `v-bind:checked`
2. Изменение радиокнопки приводит к изменению состояния через `v-on:click`

Но привязка такого `:checked` + обработка клика `@click` получается довольно громоздкой.

Именно по этому во vue есть директива двустороннего связывания `v-model`. Она сделает тоже самое, но короче. В этом случае `v-model="actions"` привяжет радиокнопки по атрибуту `value`.

2022-02-02 14:27 UTC, ShGKme commented on 01-basics/02-VueCalculator/index.html
>      </div>
Обычно у текстовой интерполяции принято добавлять пробелы: `{{ result }}`

2022-02-02 14:40 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-02-02 15:18 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-02 17:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-02-02 17:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-02-02 18:09 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-02-02 18:09 UTC, merged